import { Article } from './article';

export const ARTICLES: Article[] = [
  { id: 101,
    header: 'It',
    body: 'The terror, which would not end for another twenty-eight years-if it ever did end-began, so far as I know or can tell, with a boat made from a sheet of newspaper floating down a gutter swollen with rain. \n The boat bobbed, listed, righted itself again, dived bravely through treacherous whirlpools, and continued on its way down Witcham Street toward the traffic light which marked the intersection of Witcham and Jackson. The three vertical lenses on all sides of the traffic light were dark this afternoon in the fall of 1957, and the houses were all dark, too. There had been steady rain for a week now, and two days ago the winds had come as well. Most sections of Derry had lost their power then, and it was not back on yet.',
   userId: 1},
  { id: 102,
    header: 'Shining',
    body: 'Some of the most beautiful resort hotels in the world are located in Colorado, but the hotel in these pages is based on none of them. The Overlook and the people associated with it exist wholly within the author\'s imagination.',
    userId: 1},
  { id: 103,
    header: 'Words of Radiance',
    body: 'Jasnah Kholin pretended to enjoy the party, giving no indication that she intended to have one of the guests killed. \n She wandered through the crowded feast hall, listening as wine greased tongues and dimmed minds. Her uncle Dalinar was in the full swing of it, rising from the high table to shout for the Parshendi to bring out their drummers. Jasnah’s brother, Elhokar, hurried to shush their uncle—though the Alethi politely ignored Dalinar’s outburst. All save Elhokar’s wife, Aesudan, who snickered primly behind a handkerchief.',
    userId: 2},
  { id: 104,
    header: 'Martian',
    body: 'Our mission was designed knowing that anything might need maintenance, so I have plenty of tools. Even in a space-suit, I was able to pry the access panels off the MDV and get at the six Hydrazine tanks. I set them in the shadow of a rover to keep them from heating up too much. There’s more shade and a cooler temperature near the Hab, but fuck that. If they’re going to blow up, they can blow up a rover, not my house.',
    userId: 3},
  { id: 105,
    header: 'Harry Potter and Sorcerer\'s Stone',
    body: 'Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you\'d expect to be involved in anything strange or mysterious because they just didn\'t hold with such nonsense.',
    userId: 4},
  { id: 106,
    header: 'Harry Potter and the Chamber of Secrets',
    body: 'Harry Potter was a wizard - a wizard fresh from his first year at Hogwarts School of Witchcraft and Wizardry. And if the Dursleys were unhappy to have him back for the holidays, it was nothing to how Harry felt. \n He missed Hogwarts so much it was like having a constant stomachache. He missed the castle, with its secret passageways and ghosts, his classes (though perhaps not Snape, the Potions master), the mail arriving by owl, eating banquets in the Great Hall, sleeping in his four-poster bed in the tower dormitory, visiting the gamekeeper, Hagrid, in his cabin next to the Forbidden Forest in the grounds, and, especially, Quidditch, the most popular sport in the wizarding world (six tall goal posts, four flying balls, and fourteen players on broomsticks).',
    userId: 4},
  { id: 107,
    header: 'The Lord of the Rings. Fellowship of the Ring',
    body: 'This tale grew in the telling, until it became a history of the Great War of the Ring and included many glimpses of the yet more ancient history that preceded it. It was begun soon after The Hobbit was written and before its publication in 1937; but I did not go on with this sequel, for I wished first to complete and set in order the mythology and legends of the Elder Days, which had then been taking shape for some years. I desired to do this for my own satisfaction, and I had little hope that other people would be interested in this work, especially since it was primarily linguistic in inspiration and was begun in order to provide the necessary background of \'history\' for Elvish tongues.',
    userId: 5},
  { id: 108,
    header: 'The Lord of the Ring. Two Towers',
    body: 'Aragorn sped on up the hill. Every now and again he bent to the ground. Hobbits go light, and their footprints are not easy even for a Ranger to read, but not far from the top a spring crossed the path, and in the wet earth he saw what he was seeking.',
    userId: 5}
];
